.gitignore
.travis.yml
package.json

Hi folks,
I just did a couple of changes to our travis and package.json file, for automatic release to npmjs (under the AGCO account). This should enable us automatic pushes whenever we release to master.
Tks,
Diogo

Modified core files

---

lib/adapter.js
lib/adapters/mongodb.js

Makes mongo adapter into constructor function

---

lib/route.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/118?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/118'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Throws error on bad gets so error sending is correctly propagated

---

lib/includes.js
test/app.js
test/fixtures/collars.js
test/fixtures/foobars.js
test/includes.spec.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/126%23discussion_r36112934%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/126%23discussion_r36113913%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/126%23issuecomment-127401270%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/126%23issuecomment-127401270%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Otherwise%2C%20would%20like%20more%20comments%20%26%20more%20expressive%20fn%20names%2C%20but%20we%27re%20in%20crunch%20mode%2C%20so%20I%27m%20merging%20it%20as%20it%20is.%22%2C%20%22created_at%22%3A%20%222015-08-03T20%3A41%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%2 …

Compound documents are not returning links #125

---

lib/includes.js
test/filters.spec.js
test/fixtures/people.js
test/includes.spec.js
test/paging.spec.js
test/sorting.spec.js

- Adds new fixture for test cases
- Fixes other tests to be compatible with new fixture
<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/127?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/127'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

[#830] Fixes issue with mied includes and reduce

---

lib/includes.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/128?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/128'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

added a check around empty reduce

---

lib/includes.js
test/includes.spec.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/130%23issuecomment-130274164%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/130%23issuecomment-130274164%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hey%21%20It%20wasn%27t%20me%20%3A%29%5Cr%5Cn%5Cr%5Cn%3E%20Regarding%20the%20coveralls%22%2C%20%22created_at%22%3A%20%222015-08-12T12%3A05%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/431064%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/blabno%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img …

Bug in deep linking #129

---

lib/adapters/mongodb.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/134?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/134'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

added fix for Mongodb connection loss

---

lib/route.method.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/136%23discussion_r37906117%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%208f847fdc41eed9799b47ecb56fdd0d24e1f87a36%20lib/route.method.js%206%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/136%23discussion_r37906117%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20see%20you%27re%20sort%20of%20short-circuiting%20things%20here%2C%20which%20makes%20a%20ton%20of%20sense.%20Why%20not%20also%20do%20it%20for%20Error%20as%20well%3F%22%2C%20%22created_at%22%3A%20%222015-08-25T19%3A09%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/372075 …

Refactors harvester auth error handling

---

lib/adapter.js
lib/events-reader.js
lib/harvester.js
lib/includes.js
lib/sse.js
lib/validation.js
package.json
test/associations.spec.js
test/chaining.spec.js
test/events-reader.spec.js
test/filters.spec.js
test/includes.spec.js
test/jsonapi_error.spec.js
test/limits.spec.js
test/paging.spec.js
test/resources.spec.js
test/sorting.spec.js
test/validation.spec.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/135?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/135'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Change internal Promise lib from RSVP to Bluebird #40

---

lib/route.method.js
lib/sse.js
test/singleRouteSSE.spec.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/148%23discussion_r42122136%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20ca22954dbccd9416a689d02b4c84bc5152cc1796%20test/singleRouteSSE.spec.js%2026%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/148%23discussion_r42122136%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Can%20you%20change%20this%20to%20something%20more%20generic%3F%22%2C%20%22created_at%22%3A%20%222015-10-15T13%3A16%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/767675%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mavdi%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20test/singleRouteSSE.spec.js%3AL26-47%22%7D%7 …

SSE should be case insensitive #147

---

lib/sse.js
test/multiSSE.spec.js
test/singleRouteSSE.spec.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/150?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/150'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fixed event name, cursor timeout set to false

---

lib/sse.js
package.json
test/singleRouteSSE.spec.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/153%23discussion_r46197505%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%2059b26af7612f771da57a50fa8d97f155225dfce8%20test/singleRouteSSE.spec.js%205%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/153%23discussion_r46197505%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22drop%20the%20only%22%2C%20%22created_at%22%3A%20%222015-11-30T20%3A20%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/372075%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ssebro%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20test/singleRouteSSE.spec.js%3AL10-17%22%7D%7D%7D'></a>
<a …

Sse fix stream

---

.travis.yml
lib/adapters/mongodb.js
lib/sse.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/155?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/155'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

removed ns from initial query

---

lib/sse.js

fixes the error when running tests, also might fix the many connections issue we have with prod
<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/156?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/156'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

error handling for db

---

lib/adapters/mongodb.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/157?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/157'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fix upsert

---

lib/sse.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/160?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/160'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

removed query, no need for it only causing problems

---

lib/route.js
test/app.js
test/customHarvesterInstance.spec.js
test/filters.spec.js
test/fixtures/pets.js

Adds support for range queries.
<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/166?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/166'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Support range queries with lt, le, gt, ge

---

lib/events-reader.js
test/events-reader.spec.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/170?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/170'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Fixes events-reader filtering

---

lib/harvester.js
lib/route.js
test/app.js
test/restricted.spec.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/176%23issuecomment-246424291%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/176%23issuecomment-246431925%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/176%23issuecomment-246424291%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/7848681/badge%29%5D%28https%3A//coveralls.io/builds/7848681%29%5Cn%5CnCoverage%20increased%20%28%2B0.09%25%29%20to%2083.74%25%20when%20pulling%20%2A%2Aeb00afde01200b1a19925be3c47398645d65059d%20on%20feature/restricted%2A%2A%20in …

Adds restricted route option

---

lib/includes.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/178%23issuecomment-247381800%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/178%23issuecomment-247381800%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/7904950/badge%29%5D%28https%3A//coveralls.io/builds/7904950%29%5Cn%5CnCoverage%20increased%20%28%2B0.01%25%29%20to%2083.753%25%20when%20pulling%20%2A%2Ab47b343bc3d0c3654913c48d4d5b2ec3d8163bfc%20on%20bugfix/includes%2A%2A%20into%20%2A%2A6e014b1a8a5ddebc074402993e7031e4870d08e2%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222016-09-15T16%3A37%3A35Z%22%2C%20%22u …

Only remotely fetch unique ids.

---

lib/events-reader.js
package.json
test/events-reader.spec.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/181%23issuecomment-253824868%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/181%23issuecomment-253824868%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/8339562/badge%29%5D%28https%3A//coveralls.io/builds/8339562%29%5Cn%5CnChanges%20Unknown%20when%20pulling%20%2A%2Adf5ddfc8e9965a6ac23843d768dd6b7b003a62bd%20on%20bugfix/correct-on-change-handlers-matching%2A%2A%20into%20%2A%2A%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222016-10-14T14%3A57%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//av …

Better onChange handlers filtering

---

lib/events-reader.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/182%23issuecomment-255497154%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/182%23discussion_r84683141%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/182%23issuecomment-255497154%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/8456587/badge%29%5D%28https%3A//coveralls.io/builds/8456587%29%5Cn%5CnCoverage%20remained%20the%20same%20at%2083.841%25%20when%20pulling%20%2A%2A872d00a7f76171e44a35e0ebbdef815dc5b5ddb0%20on%20bugfix/AGCMD-3283%2A%2A%20into%20%2A%2A8fe8bf751359dabc4ee5191e886cb92aaf435a2d%20on%20develop%2A%2A …

Increase default poolSize and send keepAlives

---

README.md

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/189%23issuecomment-286860297%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/189%23issuecomment-286860297%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/10613012/badge%29%5D%28https%3A//coveralls.io/builds/10613012%29%5Cn%5CnCoverage%20remained%20the%20same%20at%2083.841%25%20when%20pulling%20%2A%2A1c8882f615971a63217c20c61b1e2b360ee92243%20on%20lucaslago%3Apatch-1%2A%2A%20into%20%2A%2A575b3def256cba3701298916436979411ebcc6eb%20on%20agco%3Adevelop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222017-03-15T19%3A57%3A22Z%22%2C% …

Fix fortune.js link

---

lib/route.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/190%23issuecomment-287878995%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/190%23issuecomment-287878995%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/10686220/badge%29%5D%28https%3A//coveralls.io/builds/10686220%29%5Cn%5CnChanges%20Unknown%20when%20pulling%20%2A%2Ae5a5d158a5e16702c06342aa938aaab62569f59b%20on%20feature/AGCMD-4008%2A%2A%20into%20%2A%2A%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222017-03-20T19%3A57%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubuserconte …

cast limit and offset to ints since mongo 3.2 is sensitive.

---

lib/events-reader.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/184%23issuecomment-255858416%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/184%23issuecomment-255860772%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/184%23issuecomment-258269961%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/184%23issuecomment-255858416%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/8484194/badge%29%5D%28https%3A//coveralls.io/builds/8484194%29%5Cn%5CnCoverage%20increased%20%28%2B0.06%25%29%20to%2083.905%25%20when%20pulling%20%2A%2A843b5f403ffc6b282216e3ac6017ee64aa54eca9%20on%20bugfix/A …

do not exit process on error

---

.travis.yml
npm-shrinkwrap.json

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/193%23issuecomment-288228335%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/193%23issuecomment-288229059%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/193%23issuecomment-288229733%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/193%23issuecomment-288228335%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/10707980/badge%29%5D%28https%3A//coveralls.io/builds/10707980%29%5Cn%5CnCoverage%20remained%20the%20same%20at%2083.918%25%20when%20pulling%20%2A%2Ab1b4bd8e0653f70b5f306791a002ed4ad8d3c6c5%20on%20lucaslago%3Au …

Update node.js to 4.2.0

---

.travis.yml
npm-shrinkwrap.json

Reverts agco/harvesterjs#193
<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/196?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/196'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/agco/harvesterjs/196)

Revert "Update node.js to 4.2.0"

---

lib/events-reader.js
npm-shrinkwrap.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/agco/harvesterjs/195)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/195%23issuecomment-288230629%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/195%23issuecomment-288230629%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/10708241/badge%29%5D%28https%3A//coveralls.io/builds/10708241%29%5Cn%5CnCoverage%20increased%20%28%2B0.04%25%29%20to%2083.954%25%20when%20pulling%20%2A%2A1df2b1447416dcf9ded013ba0474ed2ab9e1b734%20on%20fea …

Added debouncer and redid shrinkwrap.

---

.travis.yml

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/197%23issuecomment-288235145%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/197%23issuecomment-288235145%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/10708562/badge%29%5D%28https%3A//coveralls.io/builds/10708562%29%5Cn%5CnCoverage%20remained%20the%20same%20at%2083.954%25%20when%20pulling%20%2A%2A64629dd792d19daffcf8d2f681bf81afe19f613e%20on%20update-nodejs-version%2A%2A%20into%20%2A%2A55a5d7ad40af300b52a6ad3ad65dff3af4c648b1%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222017-03-21T22%3A09%3A49Z%22%2C%20%22 …

Update travis node.js version

---

lib/events-reader.js

Adds profiling to checkpoint write
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/199%23issuecomment-288244589%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/199%23issuecomment-288247242%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/199%23issuecomment-288248261%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/199%23issuecomment-288244589%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/10709282/badge%29%5D%28https%3A//coveralls.io/builds/10709282%29%5Cn%5CnCoverage%20increased%20%28%2B0.06%25%29%20to%2084.015%25%20when%20pulling%20%2A%2Acd90942bb24e0a3f424 …

Adds events reader profiling

---

lib/events-reader.js

Adds profiling to regex
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/200%23issuecomment-288251808%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/200%23issuecomment-288251808%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/10709849/badge%29%5D%28https%3A//coveralls.io/builds/10709849%29%5Cn%5CnCoverage%20increased%20%28%2B0.05%25%29%20to%2084.135%25%20when%20pulling%20%2A%2A8639c38dc5213d23266bbfa6f118af0fc1aa37a9%20on%20feature/events-reader-profiling%2A%2A%20into%20%2A%2A0774aed12e6e245dc1ac6bca49a9fe74819dca2c%20on%20develop%2A%2A.%5Cn%22%2C%20%22created_at%22%3A% …

Adds profiling to changeHandler

---

.gitignore
package.json

closes #141
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/205%23issuecomment-289788692%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/205%23issuecomment-289795612%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/205%23issuecomment-289788692%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/10809648/badge%29%5D%28https%3A//coveralls.io/builds/10809648%29%5Cn%5CnCoverage%20remained%20the%20same%20at%2084.164%25%20when%20pulling%20%2A%2A9203fea48775e94c94d54bca9a4b4fd1914decae%20on%20lucaslago%3Adont-publish-test-db%2A%2A%20into%20%2A%2A6612bddb6611b6e38c5b6f36ed60c5 …

Add db folder to .gitignore

---

docker-compose.test.yml
npm-shrinkwrap.json
package.json

We updated mongodb dependency and tested against mongo 3.4 and 2.4.14
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/209%23discussion_r108980904%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/209%23discussion_r108981519%22%2C%20%22https%3A//github.com/agco/harvesterjs/pull/209%23discussion_r108981829%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%20d10dc18edb06f7100c13bcb2445bd369c0ceaf29%20package.json%205%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/209%23discussion_r108980904%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22we%20are%20using%20the%20lib%20on%20version%202%2B%20and%20the%20mongo%20service%20on%203%2B.%20Should%20we%20update%20the%20mongdb%20lib%20version%20to%203%2B …

updating mongodb dependency

---

docker-compose.test.yml

Mongo 2.X is too outdated, we have to test harvester against the newer versions so we can use newer features.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/agco/harvesterjs/216)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/agco/harvesterjs/pull/216%23issuecomment-302214073%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/216%23issuecomment-302214073%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222017-05-17T19%3A56%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u …

upgrading mongodb for testing

---

lib/sse.js

<a href='https://www.codereviewhub.com/agco/harvesterjs/pull/218?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/agco/harvesterjs/pull/218'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/agco/harvesterjs/218)

Use mongodb.Timestamp instead of mongojs

---

lib/events-reader.js

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/ggoulart%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/10089774%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/agco/harvesterjs/pull/219%23issuecomment-303835736%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222017-05-24T20%3A03%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/10089774%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ggoulart%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222017-05-24T20%3A09%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url% …

Use mongoose in events reader

---

.npmignore

Contents of .gitignore with a couple of extra config files not required when releasing to npm.

A basic .npmignore file
